### ISSUE TITLE
Bottom Bar is now purple, used to be blue (like top)

### ISSUE THREAD

**Issue by valhuber** [nilshartmann/vscode-blue-light-theme#2]
Very much like and appreciate your work!

I have used it for a while, including screen shots in my [docs](https://apilogicserver.github.io/Docs/).  

The bottom bar is now purple, which used to be blue.  That makes my screen shots inconsistent.

Is there any way to get the blue back?

<img width="1343" alt="5-rules-cocktail" src="https://github.com/nilshartmann/vscode-blue-light-theme/assets/5579631/322056c4-ed1c-4472-a54d-bf1aab764b7d">

**Comment by valhuber** [comment]
Ah, I see, it *does* become blue when a project is loaded.  I guess purple means empty.

**Comment by nilshartmann** [comment]
Thanks for your feedback and glad you figured out where the purple comes from 😊

**Comment by valhuber** [comment]
Thanks for your theme!

Thanks,
Val

510-703-5909  valhuber on skype
